"""
Django settings for beans_and_brews project.
Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
import dj_database_url
from pathlib import Path

# 1. Core Path Definitions
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d58lpu%mfenswq_gs1o&k#sehzlzei#3!v46uv9w-)s%)yok*('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow local development and your live Render platform URL structure
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.onrender.com']


# 2. Application Definitions
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles', 
    'cloudinary',
    'menu',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beans_and_brews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beans_and_brews.wsgi.application'


# ==============================================================================
# DATABASE CONFIGURATION MATRIX (FIXED & CLEANED)
# ==============================================================================

# Check if Render is passing a live database URL string
PRODUCTION_DB_URL = os.environ.get('DATABASE_URL')

if PRODUCTION_DB_URL:
    # If it exists, force the application to use the cloud PostgreSQL database
    DATABASES = {
        'default': dj_database_url.config(
            default=PRODUCTION_DB_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # FALLBACK: If running locally on your PC, use your local PostgreSQL setup
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'beans_and_brews_db',
            'USER': 'postgres',
            'PASSWORD': 'Mini', 
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


# 4. Authentication Matrix
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# 5. Security & Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# 6. Internationalization Settings (South African Standard Time)
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Johannesburg'
USE_I18N = True
USE_TZ = True


# 7. Static & Media Delivery Assets Configuration
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Compression engine management layers
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage", # THE FIX
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}