# Generated by Django 6.0.5 on 2026-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_order_is_paid_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
